'use client';
import {useState} from 'react';
import {signOut} from 'next-auth/react';
import {useApp} from '@/components/app-provider';
import {Button,Card,Field,Input,PageHeader} from '@/components/ui';
export function SecuritySetup(){const {locale}=useApp(),ar=locale==='ar';const [password,setPassword]=useState(''),[secret,setSecret]=useState(''),[code,setCode]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function send(action:string){setBusy(true);try{const r=await fetch('/api/security',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,password,code})});const b=await r.json();if(!r.ok){setMessage(ar?'تعذر التحقق. راجع البيانات أو أعد المحاولة لاحقًا.':'Verification failed. Check the details or try again later.');return;}if(b.secret)setSecret(b.secret);else{setMessage(ar?'تم التفعيل. انتظر ظهور الرمز التالي ثم سجل الدخول.':'Enabled. Wait for the next code, then sign in.');await signOut({redirectTo:`/${locale}/login`});}}finally{setBusy(false);}}
 return <main className="mx-auto max-w-lg p-6"><PageHeader title={ar?'حماية حسابك':'Protect your account'} subtitle={ar?'التحقق بخطوتين مطلوب لحسابات فريق العمل':'Two step verification is required for staff accounts'}/><Card><Field label={ar?'كلمة المرور الحالية':'Current password'}><Input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></Field>{!secret?<Button className="mt-4" loading={busy} onClick={()=>send('setup')}>{ar?'إعداد تطبيق التحقق':'Set up authenticator'}</Button>:<><p className="my-4 text-sm">{ar?'أضف حسابًا بمفتاح إعداد داخل تطبيق التحقق. اختر رمزًا زمنيًا وأدخل المفتاح التالي.':'Add an account using a setup key in your authenticator. Choose time based codes and enter this key.'}</p><code dir="ltr" className="block break-all rounded bg-[var(--surface-sunken)] p-3">{secret}</code><Field label={ar?'الرمز المكون من ستة أرقام':'Six digit code'}><Input inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value)}/></Field><Button className="mt-4" loading={busy} onClick={()=>send('confirm')}>{ar?'تفعيل الحماية':'Enable verification'}</Button></>}{message?<p role="status" className="mt-4">{message}</p>:null}</Card></main>;
}
